import React from 'react';

const FEATURES = [
  {
    icon: '🛡️', iconBg: 'var(--accent-dim)',
    title: 'Authenticity Detection',
    desc: 'ML model detects purchased followers, engagement pods, bot activity, and artificial spikes in real time.',
    scoreLabel: 'Authenticity Score 0–100', scoreClass: 'tag-green',
  },
  {
    icon: '📈', iconBg: 'var(--blue-dim)',
    title: 'Growth Prediction',
    desc: 'LSTM time-series model forecasts follower growth, engagement trajectory, and audience expansion over 30/90/180 days.',
    scoreLabel: 'Growth Score 0–100', scoreClass: 'tag-blue',
  },
  {
    icon: '🏷️', iconBg: 'var(--gold-dim)',
    title: 'Brand Matching via RAG',
    desc: 'NLP embeddings + FAISS similarity search matches creators to brands based on content, audience, and value alignment.',
    scoreLabel: 'Brand Match 0–100', scoreClass: 'tag-gold',
  },
];

const FEATURES2 = [
  {
    icon: '🤖', iconBg: 'var(--coral-dim)',
    title: 'ML-Based Ratefluencer™ Score',
    desc: 'XGBoost champion model (AUC 0.94) trained on engagement rate, save rate, comment quality, audience demographics, content consistency, and 30+ more features. Ranks creators by predicted business impact.',
    scoreLabel: 'Ratefluencer™ Score 0–100', scoreClass: 'tag-coral',
  },
  {
    icon: '🎯', iconBg: 'var(--purple-dim)',
    title: 'Campaign Success Probability',
    desc: 'Before you spend a rupee, get a probability score for your specific campaign — accounting for budget, category, target audience, and creator fit.',
    scoreLabel: 'Success Probability 0–100%', scoreClass: 'tag-purple',
  },
];

const STEPS = [
  { num: '01', title: 'Define your campaign',          desc: 'Set your brand, budget, target audience, country, and content category. The more context you give, the smarter the recommendation.' },
  { num: '02', title: 'AI scrapes & analyzes creators', desc: 'Our pipeline collects followers, engagement, posting frequency, audience demographics, and content signals across platforms.' },
  { num: '03', title: 'Scores are computed',           desc: 'Authenticity, Growth, Brand Match, and the overall Ratefluencer™ Score are generated by our ML ensemble model.' },
  { num: '04', title: 'You get ranked recommendations', desc: 'Creators ranked by predicted ROI, not follower count. One click to shortlist, export, or start outreach.' },
];

const STATS = [
  { val: '94%',  label: 'Prediction Accuracy' },
  { val: '50,000', label: 'Creators Analyzed' },
  { val: '₹0',   label: 'Wasted on Fakes' },
];

function FeatureCard({ icon, iconBg, title, desc, scoreLabel, scoreClass }) {
  return (
    <div
      style={{ background: 'var(--bg2)', padding: '2rem', transition: 'background .2s', cursor: 'default' }}
      onMouseEnter={e => { e.currentTarget.style.background = 'var(--bg3)'; }}
      onMouseLeave={e => { e.currentTarget.style.background = 'var(--bg2)'; }}
    >
      <div style={{ width: '40px', height: '40px', borderRadius: '10px', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: '18px', marginBottom: '1.25rem', background: iconBg }}>
        {icon}
      </div>
      <div style={{ fontSize: '15px', fontWeight: 500, marginBottom: '8px' }}>{title}</div>
      <div style={{ fontSize: '13px', color: 'var(--text2)', lineHeight: 1.6 }}>{desc}</div>
      <span className={`tag ${scoreClass}`} style={{ fontFamily: 'var(--font-mono)', fontSize: '11px', marginTop: '12px', padding: '4px 10px', borderRadius: '20px', display: 'inline-block' }}>
        {scoreLabel}
      </span>
    </div>
  );
}

export default function LandingPage({ onNavigate }) {
  return (
    <div style={{ paddingTop: '56px' }}>

      {/* ── Hero ── */}
      <section style={{
        minHeight: 'calc(100vh - 56px)', display: 'flex', flexDirection: 'column',
        alignItems: 'center', justifyContent: 'center', textAlign: 'center',
        padding: '4rem 2rem', position: 'relative', overflow: 'hidden',
      }}>
        {/* Grid bg */}
        <div style={{
          position: 'absolute', inset: 0,
          backgroundImage: 'linear-gradient(rgba(255,255,255,0.02) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,0.02) 1px,transparent 1px)',
          backgroundSize: '60px 60px',
          maskImage: 'radial-gradient(ellipse 80% 60% at 50% 50%,black,transparent)',
          WebkitMaskImage: 'radial-gradient(ellipse 80% 60% at 50% 50%,black,transparent)',
        }} />
        {/* Glow */}
        <div style={{
          position: 'absolute', width: '600px', height: '600px', borderRadius: '50%',
          background: 'radial-gradient(circle,rgba(200,240,104,0.08) 0%,transparent 70%)',
          top: '50%', left: '50%', transform: 'translate(-50%,-60%)', pointerEvents: 'none',
        }} />

        <div className="hero-badge fade-up" style={{
          display: 'inline-flex', alignItems: 'center', gap: '8px',
          padding: '6px 14px', borderRadius: '20px',
          border: '1px solid rgba(200,240,104,0.25)', background: 'rgba(200,240,104,0.06)',
          fontSize: '12px', color: 'var(--accent)', marginBottom: '2rem',
          fontFamily: 'var(--font-mono)', letterSpacing: '.04em', position: 'relative',
        }}>
          <span style={{ width: '6px', height: '6px', borderRadius: '50%', background: 'var(--accent)', animation: 'pulse 2s infinite', display: 'inline-block' }} />
          Powered by Machine Learning + RAG
        </div>

        <h1 className="fade-up delay-1" style={{
          fontFamily: 'var(--font-display)', fontSize: 'clamp(42px,7vw,88px)', lineHeight: 1.05,
          color: 'var(--text)', marginBottom: '1.5rem', maxWidth: '900px', position: 'relative',
        }}>
          Find influencers that<br />
          <em style={{ color: 'var(--accent)', fontStyle: 'italic' }}>actually convert.</em>
        </h1>

        <p className="fade-up delay-2" style={{
          fontSize: '18px', color: 'var(--text2)', maxWidth: '560px', lineHeight: 1.7,
          marginBottom: '2.5rem', fontWeight: 300, position: 'relative',
        }}>
          Stop guessing with follower counts. Our AI analyzes 40+ signals — authenticity, engagement quality, growth trajectory — to predict real campaign ROI before you spend a rupee.
        </p>

        <div className="fade-up delay-3" style={{ display: 'flex', gap: '12px', alignItems: 'center', position: 'relative' }}>
          <button className="btn btn-primary" onClick={() => onNavigate('dashboard')}>Get Started →</button>
          <button className="btn btn-ghost" onClick={() => onNavigate('recommendations')}>View Demo</button>
        </div>

        <div className="fade-up delay-4" style={{
          display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: '1px',
          background: 'var(--border)', border: '1px solid var(--border)',
          borderRadius: 'var(--radius)', overflow: 'hidden',
          marginTop: '5rem', width: '100%', maxWidth: '640px', position: 'relative',
        }}>
          {STATS.map(s => (
            <div key={s.label} style={{ background: 'var(--bg2)', padding: '1.5rem', textAlign: 'center' }}>
              <div style={{ fontFamily: 'var(--font-display)', fontSize: '32px', color: 'var(--text)', marginBottom: '4px' }}>{s.val}</div>
              <div style={{ fontSize: '12px', color: 'var(--text3)', letterSpacing: '.04em', textTransform: 'uppercase' }}>{s.label}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Features ── */}
      <section style={{ padding: '6rem 2rem', maxWidth: '1100px', margin: '0 auto' }}>
        <div className="section-label">What we analyze</div>
        <div style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(28px,4vw,48px)', color: 'var(--text)', marginBottom: '1rem', lineHeight: 1.1 }}>
          Every signal that<br />matters.
        </div>
        <div style={{ fontSize: '16px', color: 'var(--text2)', marginBottom: '3rem', fontWeight: 300, maxWidth: '500px' }}>
          We go beyond the follower count. Here's what the engine looks at.
        </div>

        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(3,1fr)', gap: '1px', background: 'var(--border)', border: '1px solid var(--border)', borderRadius: 'var(--radius)', overflow: 'hidden', marginBottom: '1px' }}>
          {FEATURES.map(f => <FeatureCard key={f.title} {...f} />)}
        </div>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2,1fr)', gap: '1px', background: 'var(--border)', border: '1px solid var(--border)', borderRadius: 'var(--radius)', overflow: 'hidden' }}>
          {FEATURES2.map(f => <FeatureCard key={f.title} {...f} />)}
        </div>
      </section>

      {/* ── How it works ── */}
      <section style={{ padding: '6rem 2rem', maxWidth: '1100px', margin: '0 auto' }}>
        <div className="section-label">How it works</div>
        <div style={{ fontFamily: 'var(--font-display)', fontSize: 'clamp(28px,4vw,48px)', color: 'var(--text)', marginBottom: '3rem', lineHeight: 1.1 }}>
          Four steps to the<br />perfect creator.
        </div>
        <div>
          {STEPS.map((step, i) => (
            <div key={step.num} style={{
              display: 'grid', gridTemplateColumns: '80px 1fr', gap: '2rem',
              padding: '2rem 0', borderBottom: i < STEPS.length - 1 ? '1px solid var(--border)' : 'none',
              alignItems: 'center',
            }}>
              <div style={{ fontFamily: 'var(--font-display)', fontSize: '48px', color: 'var(--border2)', lineHeight: 1 }}>{step.num}</div>
              <div>
                <div style={{ fontSize: '18px', fontWeight: 500, marginBottom: '6px' }}>{step.title}</div>
                <div style={{ fontSize: '14px', color: 'var(--text2)', lineHeight: 1.6 }}>{step.desc}</div>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* ── CTA ── */}
      <section style={{ padding: '6rem 2rem', textAlign: 'center' }}>
        <div style={{ maxWidth: '640px', margin: '0 auto', padding: '4rem', border: '1px solid var(--border)', borderRadius: '24px', background: 'var(--bg2)', position: 'relative', overflow: 'hidden' }}>
          <div style={{ position: 'absolute', inset: 0, background: 'radial-gradient(circle at 50% 0%,rgba(200,240,104,0.06),transparent 60%)', pointerEvents: 'none' }} />
          <div style={{ fontSize: '32px', marginBottom: '1rem' }}>🚀</div>
          <h2 style={{ fontFamily: 'var(--font-display)', fontSize: '40px', marginBottom: '1rem', lineHeight: 1.1 }}>Ready to stop guessing?</h2>
          <p style={{ fontSize: '16px', color: 'var(--text2)', marginBottom: '2rem', fontWeight: 300 }}>Run your first campaign analysis free. No credit card needed.</p>
          <button className="btn btn-primary" onClick={() => onNavigate('campaign')} style={{ fontSize: '15px', padding: '14px 32px' }}>
            Analyze a Campaign →
          </button>
        </div>
      </section>

      <footer style={{ borderTop: '1px solid var(--border)', padding: '2rem', textAlign: 'center', color: 'var(--text3)', fontSize: '12px' }}>
        © 2025 Ratefluencer™ · AI Influencer Intelligence Engine · Built with ML + RAG + NLP
      </footer>
    </div>
  );
}
